"""Async-SQLAlchemy repository for ``knowly.kal_connections``.

The repository is a thin facade: each function takes an
``AsyncSession`` plus the tenant scope, and returns / mutates rows.
The service layer owns commit/rollback and the orchestration of
factory + secret-box around these calls.

All read and write operations except ``list_all`` filter by
``tenant_id`` — there is no cross-tenant read or write path. Callers
that need a cross-tenant operation (e.g. lifespan hydration) call
``list_all`` instead. ``count_for_tenant`` returns a scalar row count
so the service's per-tenant cap check stays a single round-trip.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Final

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from knowlytix.kal.connections.models import DEFAULT_STATUS, KALConnection


class KALConnectionNotFoundError(LookupError):
    """No row matched the given ``(tenant_id, row_id)`` scope.

    Subclasses ``LookupError`` so callers that already handle missing
    lookups keep working; ``isinstance`` against this class gives a
    more specific discrimination point at the service / API boundary.
    """


# Sentinel for "field omitted" on partial-update kwargs where ``None``
# is a meaningful value (clear-the-field). ``Final`` so mypy treats
# the singleton check ``is _UNSET`` as a type narrow.
class _UnsetType:
    pass


_UNSET: Final[_UnsetType] = _UnsetType()


async def create(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    name: str,
    adapter_type: str,
    config: dict[str, object],
    credentials: bytes,
    capabilities: dict[str, object] | None = None,
    status: str = DEFAULT_STATUS,
    validated_at: datetime | None = None,
) -> KALConnection:
    """Insert a row. Caller commits.

    ``credentials`` MUST already be ``KALSecretBox`` ciphertext — the
    repository never sees plaintext.
    """
    row = KALConnection(
        tenant_id=tenant_id,
        name=name,
        adapter_type=adapter_type,
        config=config,
        credentials=credentials,
        capabilities=capabilities,
        status=status,
        validated_at=validated_at,
    )
    session.add(row)
    # ``flush`` so the autogenerated ``id`` and server-side defaults
    # populate on the returned instance without forcing the caller to
    # ``await session.refresh``.
    await session.flush()
    return row


async def get_by_id(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    row_id: uuid.UUID,
) -> KALConnection:
    """Fetch a row by id, enforcing tenant scope.

    Raises ``KALConnectionNotFoundError`` if either the row doesn't
    exist or it belongs to another tenant — same error in both cases
    so a cross-tenant attacker can't distinguish "no row" from "row
    owned by someone else". The error message echoes both the row id
    (caller-supplied) and the tenant id (caller's own authenticated
    scope) for debuggability; neither field reveals information the
    caller didn't already possess.
    """
    row = (
        await session.execute(
            select(KALConnection).where(
                KALConnection.id == row_id,
                KALConnection.tenant_id == tenant_id,
            )
        )
    ).scalar_one_or_none()
    if row is None:
        raise KALConnectionNotFoundError(
            f"kal_connection {row_id} not found for tenant {tenant_id}"
        )
    return row


async def get_by_name(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    name: str,
) -> KALConnection | None:
    """Fetch a row by user-facing ``name`` within the tenant scope.

    Returns ``None`` for "no such row" — duplicate-name detection on
    create is the service-layer's job, not the repository's.
    """
    return (
        await session.execute(
            select(KALConnection).where(
                KALConnection.tenant_id == tenant_id,
                KALConnection.name == name,
            )
        )
    ).scalar_one_or_none()


async def list_for_tenant(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
) -> list[KALConnection]:
    """Tenant-scoped list in deterministic ``(created_at, id)`` order."""
    rows = (
        await session.execute(
            select(KALConnection)
            .where(KALConnection.tenant_id == tenant_id)
            .order_by(KALConnection.created_at, KALConnection.id)
        )
    ).scalars().all()
    return list(rows)


async def count_for_tenant(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
) -> int:
    """Tenant-scoped row count. The service's per-tenant cap check
    uses this rather than materialising the full ``list_for_tenant``
    result — once a tenant approaches the cap, every create would
    otherwise pay an N-row hydrate for a single integer.
    """
    return (
        await session.execute(
            select(func.count())
            .select_from(KALConnection)
            .where(KALConnection.tenant_id == tenant_id)
        )
    ).scalar_one()


async def list_all(
    session: AsyncSession,
    *,
    status: str | None = None,
) -> list[KALConnection]:
    """Cross-tenant list — used by lifespan hydration. Optional
    ``status`` filter so the boot path can read only ``'active'`` rows.
    """
    stmt = select(KALConnection).order_by(
        KALConnection.created_at, KALConnection.id
    )
    if status is not None:
        stmt = stmt.where(KALConnection.status == status)
    rows = (await session.execute(stmt)).scalars().all()
    return list(rows)


async def update(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    row_id: uuid.UUID,
    config: dict[str, object] | None = None,
    credentials: bytes | None = None,
    capabilities: dict[str, object] | None = None,
    status: str | None = None,
    last_error: str | None | _UnsetType = _UNSET,
    validated_at: datetime | None | _UnsetType = _UNSET,
) -> KALConnection:
    """Partial update inside the tenant scope.

    Field-by-field semantics: a ``None`` argument means "don't change
    this field." For the two nullable fields (``last_error``,
    ``validated_at``) that have a meaningful ``None`` value, the
    ``_UNSET`` sentinel is the don't-change marker — pass ``None``
    explicitly to clear them.

    Mutates and returns the SQLAlchemy instance; caller commits.
    """
    row = await get_by_id(session, tenant_id=tenant_id, row_id=row_id)
    if config is not None:
        row.config = config
    if credentials is not None:
        row.credentials = credentials
    if capabilities is not None:
        row.capabilities = capabilities
    if status is not None:
        row.status = status
    if not isinstance(last_error, _UnsetType):
        row.last_error = last_error
    if not isinstance(validated_at, _UnsetType):
        row.validated_at = validated_at
    await session.flush()
    return row


async def delete(
    session: AsyncSession,
    *,
    tenant_id: uuid.UUID,
    row_id: uuid.UUID,
) -> None:
    """Remove a row. Caller commits. Raises
    ``KALConnectionNotFoundError`` if the row isn't visible in the
    tenant scope — same error as ``get_by_id`` so the API can't be a
    presence oracle.
    """
    row = await get_by_id(session, tenant_id=tenant_id, row_id=row_id)
    await session.delete(row)
    await session.flush()
