#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""MCP server: general-purpose GMS expert system builder for Claude Code.

Exposes tools to create, manage, and query geometric expert systems.
Each expert system is a persistent GMS knowledge store that can be
built from documents (PDF, TeX, Markdown) and grows through verified
Q&A interactions and web research.

Usage:
    python -m knowlytix.knowledge.mcp_server [--stores-dir ./stores] [--model claude-sonnet-4-20250514]

Configure in .mcp.json (auto-generated by `knowlytix.knowledge setup`):
    {
      "mcpServers": {
        "gms": {
          "command": "python",
          "args": ["-m", "knowlytix.knowledge.mcp_server", "--stores-dir", "./gms_stores"],
          "cwd": "/path/to/project"
        }
      }
    }
"""

import argparse
import json
import os
import sys
import time

# Ensure project root is on path
_project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

import torch
from mcp.server.fastmcp import FastMCP

from knowlytix.knowledge.config import DocGMSConfig
from knowlytix.knowledge.store import GMSExpertStore
from knowlytix.knowledge.llm_backend import create_backend
from knowlytix.knowledge.query import QueryEngine

# ---------------------------------------------------------------------------
# Parse args before FastMCP takes over stdio
# ---------------------------------------------------------------------------

_parser = argparse.ArgumentParser(add_help=False)
_parser.add_argument("--stores-dir", default="gms_stores",
                     help="Directory containing all expert system stores")
_parser.add_argument("--model", default="claude-sonnet-4-20250514")
_parser.add_argument("--device", default=None)
_args, _remaining = _parser.parse_known_args()

# ---------------------------------------------------------------------------
# Server state: manages multiple expert systems
# ---------------------------------------------------------------------------

_device = torch.device(
    _args.device or ("cuda" if torch.cuda.is_available() else "cpu")
)
_stores_dir = os.path.abspath(_args.stores_dir)
os.makedirs(_stores_dir, exist_ok=True)

# Active expert system
_active: dict = {
    "name": None,
    "store": None,
    "engine": None,
    "config": None,
    "llm": None,
}


def _load_store(name: str) -> bool:
    """Load an expert system by name. Returns True on success."""
    store_path = os.path.join(_stores_dir, name)
    if not os.path.isdir(store_path):
        return False

    config = DocGMSConfig(store_path=store_path)
    config.convert.llm_model = _args.model
    store = GMSExpertStore(config, _device)

    if not store.load():
        return False

    llm = create_backend(config.convert)
    engine = QueryEngine(store, llm, config)

    _active["name"] = name
    _active["store"] = store
    _active["engine"] = engine
    _active["config"] = config
    _active["llm"] = llm
    return True


def _create_store(name: str) -> GMSExpertStore:
    """Create a new empty expert system."""
    store_path = os.path.join(_stores_dir, name)
    os.makedirs(store_path, exist_ok=True)

    config = DocGMSConfig(store_path=store_path)
    config.convert.llm_model = _args.model
    store = GMSExpertStore(config, _device)
    llm = create_backend(config.convert)
    engine = QueryEngine(store, llm, config)

    _active["name"] = name
    _active["store"] = store
    _active["engine"] = engine
    _active["config"] = config
    _active["llm"] = llm
    return store


def _ensure_active() -> str | None:
    """Ensure an expert system is active. Returns error message or None."""
    if _active["store"] is not None:
        return None
    # Try to auto-load if there's exactly one store
    stores = _list_stores()
    if len(stores) == 1:
        if _load_store(stores[0]["name"]):
            return None
    if len(stores) == 0:
        return ("No expert systems found. Use gms_create to create one, "
                "or gms_ingest to create one from a document.")
    return (f"Multiple expert systems available: "
            f"{[s['name'] for s in stores]}. "
            f"Use gms_use to select one.")


def _list_stores() -> list[dict]:
    """List all expert system stores."""
    stores = []
    if not os.path.isdir(_stores_dir):
        return stores
    for name in sorted(os.listdir(_stores_dir)):
        store_path = os.path.join(_stores_dir, name)
        if not os.path.isdir(store_path):
            continue
        meta_path = os.path.join(store_path, "metadata.json")
        info = {"name": name, "path": store_path}
        if os.path.isfile(meta_path):
            with open(meta_path) as f:
                meta = json.load(f)
            info["documents"] = len(meta.get("documents", []))
            info["last_saved"] = meta.get("last_saved", "")
        # Count triples
        triples_path = os.path.join(store_path, "triples.json")
        if os.path.isfile(triples_path):
            with open(triples_path) as f:
                info["triples"] = len(json.load(f))
        else:
            info["triples"] = 0
        # Count ENM
        enm_path = os.path.join(store_path, "enm.json")
        if os.path.isfile(enm_path):
            with open(enm_path) as f:
                info["enm_entries"] = len(json.load(f))
        else:
            info["enm_entries"] = 0

        stores.append(info)
    return stores


# Auto-load if there's a single store
_auto_stores = _list_stores()
if len(_auto_stores) == 1:
    _load_store(_auto_stores[0]["name"])
elif len(_auto_stores) > 1:
    # Load the most recently saved one
    _auto_stores.sort(key=lambda s: s.get("last_saved", ""), reverse=True)
    _load_store(_auto_stores[0]["name"])


# ---------------------------------------------------------------------------
# MCP Server
# ---------------------------------------------------------------------------

mcp = FastMCP(
    "GMS Expert System Builder",
    instructions=(
        "Build and query geometric expert systems from documents. "
        "Use gms_create to create a new expert system, gms_ingest to "
        "add documents, gms_query to ask questions, gms_search to find "
        "connections, and gms_list to see all expert systems."
    ),
)


# ===== Store Management =====

@mcp.tool()
def gms_create(name: str, description: str = "") -> str:
    """Create a new expert system.

    Creates an empty geometric knowledge store that can be populated
    by ingesting documents or through Q&A interactions.

    Args:
        name: Name for the expert system (used as directory name).
              Use a short, descriptive name like "pharma", "legal", "ml-papers".
        description: Optional description of what this expert system covers.

    Returns:
        JSON confirmation with store path.
    """
    name = name.strip().replace(" ", "-").lower()
    store_path = os.path.join(_stores_dir, name)

    if os.path.isdir(store_path):
        # Already exists — just switch to it
        if _load_store(name):
            stats = _active["store"].stats()
            return json.dumps({
                "status": "already_exists",
                "name": name,
                "store": stats,
                "message": f"Expert system '{name}' already exists. Now active.",
            }, indent=2)

    store = _create_store(name)

    # Save description as metadata
    meta = {
        "created": time.strftime("%Y-%m-%d %H:%M:%S"),
        "description": description,
        "documents": [],
    }
    os.makedirs(store_path, exist_ok=True)
    with open(os.path.join(store_path, "metadata.json"), "w") as f:
        json.dump(meta, f, indent=2)

    return json.dumps({
        "status": "created",
        "name": name,
        "path": store_path,
        "description": description,
        "message": (f"Expert system '{name}' created. "
                    f"Use gms_ingest to add documents."),
    }, indent=2)


@mcp.tool()
def gms_list() -> str:
    """List all available expert systems.

    Returns:
        JSON with list of expert systems, their sizes, and which is active.
    """
    stores = _list_stores()
    return json.dumps({
        "active": _active["name"],
        "stores_dir": _stores_dir,
        "expert_systems": stores,
        "total": len(stores),
    }, indent=2)


@mcp.tool()
def gms_use(name: str) -> str:
    """Switch to a different expert system.

    Args:
        name: Name of the expert system to activate.

    Returns:
        JSON confirmation with store statistics.
    """
    name = name.strip().lower()
    if _active["name"] == name:
        stats = _active["store"].stats() if _active["store"] else {}
        return json.dumps({
            "status": "already_active",
            "name": name,
            "store": stats,
        }, indent=2)

    if _load_store(name):
        stats = _active["store"].stats()
        return json.dumps({
            "status": "switched",
            "name": name,
            "store": stats,
        }, indent=2)

    return json.dumps({
        "error": f"Expert system '{name}' not found",
        "available": [s["name"] for s in _list_stores()],
    }, indent=2)


# ===== Knowledge Operations =====

@mcp.tool()
def gms_ingest(document_path: str, name: str = "", epochs: int = 200) -> str:
    """Ingest a document into an expert system.

    Converts the document to markdown, extracts knowledge triples and
    numeric values, trains geometric embeddings, and saves the store.
    If no expert system is active, creates one from the document name.

    Supports: PDF, TeX/LaTeX, Markdown, plain text.

    Args:
        document_path: Path to the document file.
        name: Expert system name. If empty, derives from document name
              or uses the active expert system.
        epochs: Training epochs for embedding learning (default 200).

    Returns:
        JSON with ingestion results and store statistics.
    """
    from knowlytix.knowledge.ingest import ingest_document

    document_path = os.path.abspath(document_path)
    if not os.path.isfile(document_path):
        return json.dumps({"error": f"File not found: {document_path}"})

    # Determine which store to use
    if name:
        store_name = name.strip().replace(" ", "-").lower()
    elif _active["name"]:
        store_name = _active["name"]
    else:
        # Derive name from document filename
        base = os.path.splitext(os.path.basename(document_path))[0]
        store_name = base.strip().replace(" ", "-").lower()[:40]

    # Create or switch to the store
    store_path = os.path.join(_stores_dir, store_name)
    if os.path.isdir(store_path) and _active["name"] != store_name:
        _load_store(store_name)
    elif not os.path.isdir(store_path):
        _create_store(store_name)

    config = _active["config"]
    config.train.epochs = epochs

    result = ingest_document(
        _active["store"], document_path, _active["llm"], config, _device,
    )

    # Reinitialise engine with updated store
    _active["engine"] = QueryEngine(
        _active["store"], _active["llm"], config,
    )

    stats = _active["store"].stats()
    return json.dumps({
        "status": "success",
        "expert_system": store_name,
        "document": document_path,
        "store": stats,
        "message": (f"Document ingested into '{store_name}'. "
                    f"{stats['triples']} triples, "
                    f"{stats['enm_entries']} exact values."),
    }, indent=2)


@mcp.tool()
def gms_query(question: str, mode: str = "gms_llm") -> str:
    """Query the active expert system.

    Answers questions using a three-tier fallback:
      1. GMS structured answer (exact recall, triple search, counting)
      2. LLM grounded in the ingested document + GMS geometric context
      3. Web agent: searches the web, verifies against GMS, merges new knowledge

    The expert system grows over time: verified facts from LLM answers
    and web research are merged into the geometric store.

    Args:
        question: The question to ask.
        mode: "gms_llm" (full pipeline, default),
              "gms_only" (geometric store only, no LLM),
              "llm_only" (LLM with document, verified by GMS).

    Returns:
        JSON with answer, source, confidence, and provenance.
    """
    err = _ensure_active()
    if err:
        return json.dumps({"error": err})

    if mode not in ("gms_only", "llm_only", "gms_llm"):
        mode = "gms_llm"

    result = _active["engine"].query(question, mode=mode)

    output = {
        "expert_system": _active["name"],
        "answer": result.answer,
        "source": result.source,
        "source_detail": result.source_detail,
        "confidence": round(result.confidence, 4),
        "confidence_method": result.confidence_method,
    }

    if result.web_sources:
        output["web_sources"] = [
            {"title": s.title, "url": s.url, "consistent": s.is_consistent}
            for s in result.web_sources
        ]
        output["triples_merged"] = result.triples_merged

    if result.verification:
        v = result.verification
        output["verification"] = {
            "consistent": v.overall_consistent,
            "contradictions": sum(
                1 for c in v.contradictions if c.is_contradiction
            ),
            "holonomy_violations": sum(
                1 for h in v.inconsistencies if not h.is_consistent
            ),
        }

    if result.learned and result.learn_result:
        output["learned"] = result.learn_result.reason

    return json.dumps(output, indent=2)


@mcp.tool()
def gms_search(concepts: str, max_hops: int = 5) -> str:
    """Find geometric paths connecting concepts in the knowledge store.

    Uses BFS to discover paths between concept entity groups, then
    scores each path by composing learned Cayley rotors and measuring
    geodesic distance on the hypersphere. Lower score = more plausible.

    Args:
        concepts: Comma-separated concept words (e.g. "bivector,steering"
                  or "warfarin,enzyme").
        max_hops: Maximum path length (default 5).

    Returns:
        JSON with paths ranked by geometric score, and related triples.
    """
    err = _ensure_active()
    if err:
        return json.dumps({"error": err})

    engine = _active["engine"]
    if engine._geo_search is None:
        return json.dumps({
            "error": "No geometric search available (store has no trained model)"
        })

    concept_list = [c.strip().lower() for c in concepts.split(",") if c.strip()]
    if len(concept_list) < 2:
        return json.dumps({
            "error": "Provide at least 2 comma-separated concepts"
        })

    concept_groups = engine._group_entities_by_concept(concept_list)
    if not concept_groups:
        return json.dumps({
            "error": "No entities matched any concepts",
            "concepts_searched": concept_list,
        })

    result = engine._geo_search.connect_concept_groups(
        concept_groups, max_hops,
    )

    paths_out = []
    for p in result.paths:
        paths_out.append({
            "entities": p.entity_names,
            "relations": p.relation_names,
            "geodesic": round(p.geodesic, 4),
            "hops": p.hops,
        })

    triples_out = []
    for h, r, t in result.all_triples:
        if r != "in_section":
            triples_out.append(f"{h} | {r} | {t}")

    matched = {c: len(ents) for c, ents in concept_groups.items()}

    return json.dumps({
        "expert_system": _active["name"],
        "concepts_matched": matched,
        "paths_found": len(result.paths),
        "n_hops": result.n_hops,
        "best_geodesic": (round(result.best_geodesic, 4)
                          if result.best_geodesic else None),
        "paths": paths_out[:10],
        "triples": triples_out[:30],
    }, indent=2)


@mcp.tool()
def gms_lookup(entity: str) -> str:
    """Look up everything the expert system knows about an entity.

    Returns all triples involving the entity (as head or tail),
    exact numeric values from the ENM register, and the entity's
    geometric confidence score.

    Args:
        entity: Entity name (fuzzy matching applied).

    Returns:
        JSON with triples, ENM values, and geometric scores.
    """
    err = _ensure_active()
    if err:
        return json.dumps({"error": err})

    store = _active["store"]
    engine = _active["engine"]

    matched = store.fuzzy_match_entity(entity)
    if not matched:
        candidates = engine._match_entities(entity.lower())
        if candidates:
            matched = candidates[0]

    if not matched:
        return json.dumps({"error": f"No entity matching '{entity}'"})

    head_triples = [
        {"relation": r, "tail": t}
        for h, r, t in store.query_triples(head=matched)
        if r != "in_section"
    ]
    tail_triples = [
        {"head": h, "relation": r}
        for h, r, t in store.query_triples(tail=matched)
        if r != "in_section"
    ]

    enm_values = {}
    if store.enm:
        for key in store.enm.keys():
            if (matched.lower() in key.id.lower()
                    or key.id.lower() in matched.lower()):
                val = store.lookup_enm(key.type, key.id)
                if val is not None:
                    enm_values[f"{key.type}/{key.id}"] = val

    all_triples = (list(store.query_triples(head=matched))
                   + list(store.query_triples(tail=matched)))
    conf = engine._triple_set_confidence(all_triples[:20])

    return json.dumps({
        "expert_system": _active["name"],
        "entity": matched,
        "as_head": head_triples[:20],
        "as_tail": tail_triples[:20],
        "enm_values": enm_values,
        "geometric_confidence": round(conf, 4),
        "total_triples": len(head_triples) + len(tail_triples),
    }, indent=2)


@mcp.tool()
def gms_status() -> str:
    """Show the active expert system's knowledge store statistics.

    Returns:
        JSON with entity/relation/triple/ENM counts, sample entities,
        and sample relations.
    """
    err = _ensure_active()
    if err:
        return json.dumps({"error": err})

    store = _active["store"]
    stats = store.stats()

    sample_entities = []
    sample_relations = []
    if store.adapter:
        ents = sorted(store.adapter.entity_to_idx.keys(), key=len)
        sample_entities = ents[:20]
        sample_relations = list(store.adapter.relation_to_idx.keys())[:20]

    # Read description from metadata
    description = ""
    meta_path = os.path.join(stats["store_path"], "metadata.json")
    if os.path.isfile(meta_path):
        with open(meta_path) as f:
            meta = json.load(f)
        description = meta.get("description", "")

    return json.dumps({
        "expert_system": _active["name"],
        "description": description,
        **stats,
        "sample_entities": sample_entities,
        "sample_relations": sample_relations,
        "device": str(_device),
    }, indent=2)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    mcp.run(transport="stdio")
